-- Lofoten Peaks Supabase schema
-- Run this in the Supabase SQL editor after creating the project.

create extension if not exists postgis with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create type public.difficulty_level as enum ('easy', 'moderate', 'hard', 'expert');
create type public.moderation_status as enum ('pending', 'approved', 'rejected');
create type public.poster_route_status as enum ('draft', 'ordered', 'archived');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  points_total integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (username is null or username ~ '^[a-zA-Z0-9_]{3,24}$')
);

create table public.mountains (
  id text primary key,
  slug text not null unique,
  name text not null,
  region text not null,
  height_meters integer,
  summit extensions.geography(point, 4326),
  difficulty public.difficulty_level not null default 'moderate',
  summary text,
  description text,
  weather_location_id text,
  hero_image_path text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.trails (
  id text primary key,
  mountain_id text not null references public.mountains(id) on delete cascade,
  slug text not null unique,
  name text not null,
  summary text,
  description text,
  length_km numeric(5, 2),
  elevation_gain_meters integer,
  estimated_duration text,
  difficulty public.difficulty_level not null default 'moderate',
  start_point extensions.geography(point, 4326),
  end_point extensions.geography(point, 4326),
  route_geojson jsonb,
  route_note text,
  gpx_storage_path text,
  safety_notes jsonb not null default '[]'::jsonb,
  guide jsonb not null default '{}'::jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.trail_images (
  id bigint generated by default as identity primary key,
  trail_id text not null references public.trails(id) on delete cascade,
  file_path text not null,
  alt text,
  source text,
  license text,
  credit_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.check_ins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  mountain_id text not null references public.mountains(id) on delete cascade,
  trail_id text references public.trails(id) on delete set null,
  checked_in_at timestamptz not null default now(),
  check_in_day date not null default current_date,
  location extensions.geography(point, 4326),
  distance_to_summit_meters numeric(8, 2),
  points integer not null default 10,
  note text,
  photo_path text,
  status public.moderation_status not null default 'approved',
  created_at timestamptz not null default now(),
  unique (user_id, mountain_id, check_in_day)
);

create table public.comments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  mountain_id text references public.mountains(id) on delete cascade,
  trail_id text references public.trails(id) on delete cascade,
  parent_comment_id uuid references public.comments(id) on delete cascade,
  body text not null,
  status public.moderation_status not null default 'approved',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comment_target check (mountain_id is not null or trail_id is not null),
  constraint comment_body_length check (char_length(body) between 2 and 1200)
);

create table public.user_hikes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  mountain_id text references public.mountains(id) on delete set null,
  trail_id text references public.trails(id) on delete set null,
  title text not null,
  body text,
  difficulty public.difficulty_level,
  route_geojson jsonb,
  gpx_storage_path text,
  status public.moderation_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.poster_routes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  gpx_storage_path text,
  route_geojson jsonb,
  preview_image_path text,
  status public.poster_route_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shop_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  poster_route_id uuid references public.poster_routes(id) on delete set null,
  provider text not null,
  provider_order_id text,
  status text not null default 'created',
  amount_cents integer,
  currency text default 'NOK',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace view public.leaderboard
with (security_invoker = true) as
select
  p.id as user_id,
  coalesce(p.display_name, p.username, 'Hiker') as display_name,
  p.avatar_url,
  coalesce(sum(c.points) filter (where c.status = 'approved'), 0)::integer as points,
  count(c.id) filter (where c.status = 'approved')::integer as check_in_count,
  max(c.checked_in_at) filter (where c.status = 'approved') as last_check_in_at
from public.profiles p
left join public.check_ins c on c.user_id = p.id
group by p.id, p.display_name, p.username, p.avatar_url
order by points desc, check_in_count desc, last_check_in_at asc nulls last;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger mountains_set_updated_at
before update on public.mountains
for each row execute function public.set_updated_at();

create trigger trails_set_updated_at
before update on public.trails
for each row execute function public.set_updated_at();

create trigger comments_set_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create trigger user_hikes_set_updated_at
before update on public.user_hikes
for each row execute function public.set_updated_at();

create trigger poster_routes_set_updated_at
before update on public.poster_routes
for each row execute function public.set_updated_at();

create trigger shop_orders_set_updated_at
before update on public.shop_orders
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', new.email),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.mountains enable row level security;
alter table public.trails enable row level security;
alter table public.trail_images enable row level security;
alter table public.check_ins enable row level security;
alter table public.comments enable row level security;
alter table public.user_hikes enable row level security;
alter table public.poster_routes enable row level security;
alter table public.shop_orders enable row level security;

create policy "Profiles are public to read"
on public.profiles for select
using (true);

create policy "Users can update own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Published mountains are public"
on public.mountains for select
using (published = true);

create policy "Published trails are public"
on public.trails for select
using (published = true);

create policy "Trail images are public"
on public.trail_images for select
using (true);

create policy "Approved check-ins are public"
on public.check_ins for select
using (status = 'approved' or auth.uid() = user_id);

create policy "Users can create own check-ins"
on public.check_ins for insert
with check (auth.uid() = user_id and status = 'approved' and points = 10);

create policy "Approved comments are public"
on public.comments for select
using (status = 'approved' or auth.uid() = user_id);

create policy "Users can create own comments"
on public.comments for insert
with check (auth.uid() = user_id and status = 'approved');

create policy "Approved user hikes are public"
on public.user_hikes for select
using (status = 'approved' or auth.uid() = user_id);

create policy "Users can create own hikes"
on public.user_hikes for insert
with check (auth.uid() = user_id and status = 'pending');

create policy "Poster routes are private to owner"
on public.poster_routes for select
using (auth.uid() = user_id);

create policy "Users can create own poster routes"
on public.poster_routes for insert
with check (auth.uid() = user_id);

create policy "Users can update own poster routes"
on public.poster_routes for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can read own shop orders"
on public.shop_orders for select
using (auth.uid() = user_id);

create index mountains_slug_idx on public.mountains (slug);
create index trails_slug_idx on public.trails (slug);
create index trails_mountain_id_idx on public.trails (mountain_id);
create index check_ins_user_id_idx on public.check_ins (user_id);
create index check_ins_mountain_id_idx on public.check_ins (mountain_id);
create index comments_mountain_id_idx on public.comments (mountain_id);
create index comments_trail_id_idx on public.comments (trail_id);
create index user_hikes_user_id_idx on public.user_hikes (user_id);
create index poster_routes_user_id_idx on public.poster_routes (user_id);
