-- Initial setup content for Lofoten Peaks.
--
-- Treat this file as a one-time starter import, not as the live content source.
-- Admin edits are saved in Supabase and are not written back here.
-- Conflict handling intentionally uses DO NOTHING so rerunning this file does
-- not overwrite mountains, trails, images, GPX data, or guide text edited in Admin.

insert into public.mountains (
  id,
  slug,
  name,
  region,
  height_meters,
  summit,
  difficulty,
  summary,
  description,
  weather_location_id,
  hero_image_path
) values
  (
    'reinebringen',
    'reinebringen',
    'Reinebringen',
    'Moskenesøya, Moskenes',
    484,
    extensions.st_setsrid(extensions.st_makepoint(13.07652, 67.927689), 4326)::extensions.geography,
    'hard',
    'Iconic steep stair hike above Reine with one of Lofoten''s most famous fjord views.',
    'Reinebringen is one of Lofoten''s most photographed hikes, climbing steeply from the old road by Ramsviktunnelen to a panoramic ridge above Reine, Sakrisøy, Hamnøy and Reinefjorden.',
    'west-lofoten',
    '/images/reinebringen-hero.jpg'
  ),
  (
    'ryten-kvalvika',
    'ryten-kvalvika',
    'Ryten / Kvalvika',
    'Flakstadøya, Flakstad',
    543,
    extensions.st_setsrid(extensions.st_makepoint(13.09263, 68.08904), 4326)::extensions.geography,
    'moderate',
    'Classic hike to the Ryten viewpoint over Kvalvika Beach, with optional beach extension.',
    'Ryten is a popular summit above Kvalvika Beach, offering one of the best coastal viewpoints in Lofoten.',
    'west-lofoten',
    '/images/ryten-kvalvika-hero.jpg'
  ),
  (
    'festvagtind',
    'festvagtind',
    'Festvågtind',
    'Austvågøya, Vågan',
    541,
    extensions.st_setsrid(extensions.st_makepoint(14.225311, 68.178048), 4326)::extensions.geography,
    'hard',
    'Short, steep summit hike above Henningsvær with dramatic views over the fishing village.',
    'Festvågtind rises sharply above the road to Henningsvær and is one of the most popular short summit hikes in eastern Lofoten.',
    'east-lofoten',
    '/images/festvagtind-hero.jpg'
  ),
  (
    'offersoykammen',
    'offersoykammen',
    'Offersøykammen',
    'Vestvågøya, Vestvågøy',
    436,
    extensions.st_setsrid(extensions.st_makepoint(13.501912, 68.161276), 4326)::extensions.geography,
    'moderate',
    'Short but steep climb to a panoramic viewpoint over beaches, fjords and the Nappstraumen area.',
    'Offersøykammen is a compact mountain near the Nappstraumen tunnel and Leknes with broad views over beaches, fjords and surrounding mountains.',
    'central-lofoten',
    '/images/offersoykammen-hero.jpg'
  ),
  (
    'tjeldbergtind',
    'tjeldbergtind',
    'Tjeldbergtind',
    'Austvågøya, Vågan',
    367,
    extensions.st_setsrid(extensions.st_makepoint(14.49932, 68.229662), 4326)::extensions.geography,
    'moderate',
    'Accessible Svolvær-area hike with views over Svolvær, Kabelvåg, Vestfjorden and surrounding peaks.',
    'Tjeldbergtind is a popular local hike between Svolvær and Kabelvåg with a rewarding 360-degree view.',
    'east-lofoten',
    '/images/tjeldbergtind-hero.jpg'
  ),
  (
    'himmeltindan',
    'himmeltindan',
    'Himmeltindan',
    'Vestvågøya, Vestvågøy',
    962,
    extensions.st_setsrid(extensions.st_makepoint(13.573159, 68.221006), 4326)::extensions.geography,
    'hard',
    'Highest mountain on Vestvågøy, climbing steeply from Haukland Beach to a major Lofoten panorama.',
    'Himmeltindan is one of the major summit hikes in central Lofoten and climbs steadily from Haukland Beach toward the upper ridge.',
    'central-lofoten',
    '/images/himmeltindan-hero.jpg'
  ),
  (
    'mannen',
    'mannen',
    'Mannen',
    'Vestvågøya, Vestvågøy',
    400,
    extensions.st_setsrid(extensions.st_makepoint(13.520262, 68.203696), 4326)::extensions.geography,
    'moderate',
    'Short Haukland Beach summit hike with big views over Haukland, Uttakleiv and Vik.',
    'Mannen is a relatively accessible summit starting from the Haukland Beach area with excellent beach and mountain views.',
    'central-lofoten',
    '/images/mannen-hero.jpg'
  ),
  (
    'munken',
    'munken',
    'Munken',
    'Moskenesøya, Moskenes',
    769,
    extensions.st_setsrid(extensions.st_makepoint(13.019111, 67.93249), 4326)::extensions.geography,
    'hard',
    'Longer mountain hike from Sørvågen via lakes and Munkebu toward a wild Moskenesøya panorama.',
    'Munken is a longer and more committing hike near Sørvågen through lakes, rocky sections, boggy areas and views toward Munkebu.',
    'west-lofoten',
    '/images/munken-hero.jpg'
  )
on conflict (id) do nothing;

-- Additional popular Lofoten mountain guide drafts.
-- These are starter records for Admin review. Keep them as drafts until images,
-- GPX routes, summit coordinates, and local access notes have been verified.

insert into public.mountains (
  id,
  slug,
  name,
  region,
  height_meters,
  summit,
  check_in_radius_meters,
  difficulty,
  summary,
  description,
  weather_location_id,
  hero_image_path,
  published
) values
  (
    'floya-djevelporten',
    'floya-djevelporten',
    'Fløya / Djevelporten',
    'Austvågøya, Vågan',
    590,
    extensions.st_setsrid(extensions.st_makepoint(14.6012, 68.2483), 4326)::extensions.geography,
    400,
    'hard',
    'Steep Svolvær-area hike to the famous Djevelporten boulder and the Fløya viewpoint.',
    'Fløya and Djevelporten are among the most popular mountain objectives above Svolvær. The hike climbs quickly from town through rocky terrain to the Djevelporten boulder, with an optional continuation toward Fløya for a higher view over Svolvær, Vestfjorden and surrounding peaks.',
    'east-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'glomtinden',
    'glomtinden',
    'Glomtinden',
    'Austvågøya, Vågan',
    419,
    extensions.st_setsrid(extensions.st_makepoint(14.3067, 68.2145), 4326)::extensions.geography,
    400,
    'moderate',
    'Short ridge hike near Rørvikstranda with open views across Vestfjorden and eastern Lofoten.',
    'Glomtinden is a compact and popular hike between Henningsvær and Kabelvåg. It is lower than many Lofoten summits, but the ridge gives wide views over Rørvikstranda, Vestfjorden, Austvågøya and nearby islands.',
    'east-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'matmora',
    'matmora',
    'Matmora',
    'Austvågøya, Vågan',
    788,
    extensions.st_setsrid(extensions.st_makepoint(14.637, 68.3605), 4326)::extensions.geography,
    500,
    'hard',
    'Longer ridge hike on northern Austvågøya with big ocean and mountain views.',
    'Matmora is a classic northern Lofoten ridge hike above the Laukvik and Delp area. The route is usually longer and more exposed to weather than the short summit hikes, rewarding hikers with broad views toward the open sea, Vesterålen and the jagged interior of Austvågøya.',
    'east-lofoten',
    '/images/matmorapanorama.png',
    false
  ),
  (
    'justadtinden',
    'justadtinden',
    'Justadtinden',
    'Vestvågøya, Vestvågøy',
    738,
    extensions.st_setsrid(extensions.st_makepoint(13.758, 68.179), 4326)::extensions.geography,
    500,
    'moderate',
    'Long but steady Vestvågøya hike with a spacious summit panorama over central Lofoten.',
    'Justadtinden is a popular central Lofoten summit because the hiking is generally less technical than many coastal peaks. The route is still long, exposed to changing weather, and best treated as a proper half-day mountain hike.',
    'central-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'holandsmelen',
    'holandsmelen',
    'Holandsmelen',
    'Vestvågøya, Vestvågøy',
    434,
    extensions.st_setsrid(extensions.st_makepoint(13.493, 68.222), 4326)::extensions.geography,
    400,
    'moderate',
    'Accessible summit above Haukland and Uttakleiv with turquoise beach views.',
    'Holandsmelen is a short and rewarding mountain above the Haukland and Uttakleiv area. It is a good option when you want a proper summit feel without committing to one of the longer high peaks.',
    'central-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'hoven-gimsoya',
    'hoven-gimsoya',
    'Hoven',
    'Gimsøya, Vågan',
    368,
    extensions.st_setsrid(extensions.st_makepoint(14.230, 68.326), 4326)::extensions.geography,
    400,
    'easy',
    'Short Gimsøya summit hike above Hov with ocean views and a gentler profile than many Lofoten peaks.',
    'Hoven rises above the Hov area on Gimsøya and is one of the more approachable Lofoten mountain hikes. The summit gives broad views over beaches, farmland, open sea and the island chain.',
    'east-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'volandstinden',
    'volandstinden',
    'Volandstinden',
    'Flakstadøya, Flakstad',
    457,
    extensions.st_setsrid(extensions.st_makepoint(13.233, 68.087), 4326)::extensions.geography,
    500,
    'hard',
    'Distinctive Flakstadøya summit with coastal views toward Ramberg, Skjelfjord and surrounding ridges.',
    'Volandstinden is a sharp and scenic mountain on Flakstadøya. The route is shorter than many full-day hikes, but the terrain is steep enough that conditions and footing matter.',
    'west-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'stornappstinden',
    'stornappstinden',
    'Stornappstinden',
    'Flakstadøya, Flakstad',
    740,
    extensions.st_setsrid(extensions.st_makepoint(13.350, 68.102), 4326)::extensions.geography,
    500,
    'hard',
    'Steep summit above Napp with wide views over Flakstadøya, Vestvågøya and the Nappstraumen area.',
    'Stornappstinden is a strong mountain objective near Napp. The climb is relatively direct and gives a large panorama over the island chain, but it should be saved for clear weather and dry terrain.',
    'west-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'helvetestinden',
    'helvetestinden',
    'Helvetestinden',
    'Moskenesøya, Moskenes',
    602,
    extensions.st_setsrid(extensions.st_makepoint(12.960, 67.975), 4326)::extensions.geography,
    500,
    'hard',
    'Remote summit above Bunes Beach, usually reached by ferry to Vindstad.',
    'Helvetestinden is a dramatic mountain above Bunes Beach on Moskenesøya. The approach usually involves the ferry from Reine to Vindstad before hiking toward Bunes, then climbing steep terrain to the summit area.',
    'west-lofoten',
    '/images/homebanner.png',
    false
  ),
  (
    'roren',
    'roren',
    'Røren',
    'Flakstadøya, Flakstad',
    295,
    extensions.st_setsrid(extensions.st_makepoint(13.170, 68.105), 4326)::extensions.geography,
    400,
    'easy',
    'Short coastal viewpoint above Ytresand and Fredvang with strong sunset potential.',
    'Røren is a lower coastal hike near Fredvang and Ytresand. It is popular because it gives a large view over beaches, bridges, open sea and surrounding mountains for a relatively modest effort.',
    'west-lofoten',
    '/images/homebanner.png',
    false
  )
on conflict (id) do nothing;

insert into public.trails (
  id,
  mountain_id,
  slug,
  name,
  summary,
  description,
  length_km,
  elevation_gain_meters,
  estimated_duration,
  difficulty,
  start_point,
  end_point,
  route_note,
  safety_notes,
  published
) values
  (
    'floya-djevelporten',
    'floya-djevelporten',
    'floya-djevelporten',
    'Fløya / Djevelporten',
    'Steep Svolvær-area hike to Djevelporten and the Fløya viewpoint.',
    'The route starts close to Svolvær and climbs steeply through rocky terrain toward Djevelporten. Continuing toward Fløya adds height, exposure and a stronger summit view.',
    4.0,
    590,
    '3-5 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(14.5765, 68.2348), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.6012, 68.2483), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Steep rocky sections can be slippery after rain.', 'Do not climb onto exposed photo spots in wind or wet conditions.', 'Several variants exist near Svolvaer; use a map or GPX route.'),
    false
  ),
  (
    'glomtinden',
    'glomtinden',
    'glomtinden',
    'Glomtinden',
    'Short ridge hike with views over Rørvikstranda and Vestfjorden.',
    'Glomtinden is a relatively short hike, but the ridge and upper slopes still need care in wind, wet grass or winter conditions.',
    4.0,
    350,
    '2-3 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(14.287, 68.206), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.3067, 68.2145), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Grass and rocks can be slippery after rain.', 'Watch wind exposure on the ridge.', 'Parking and trailhead access should be checked locally.'),
    false
  ),
  (
    'matmora',
    'matmora',
    'matmora',
    'Matmora',
    'Longer northern Austvågøya ridge hike with open sea views.',
    'Matmora is normally treated as a longer mountain day. The route can be done from the Delp/Laukvik side depending on local choices and transport.',
    13.1,
    780,
    '5-7 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(14.735, 68.356), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.637, 68.3605), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Long route with sustained exposure to coastal weather.', 'Carry enough water, layers and navigation.', 'Avoid the ridge in poor visibility or strong wind.'),
    false
  ),
  (
    'justadtinden',
    'justadtinden',
    'justadtinden',
    'Justadtinden',
    'Long and steady central Lofoten summit hike.',
    'Justadtinden is less technical than many Lofoten peaks, but the distance and exposed plateau make weather planning important.',
    12.3,
    730,
    '5-7 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.735, 68.170), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.758, 68.179), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Long distance for a moderate route; start with enough time.', 'Open terrain is exposed to wind and fog.', 'Wet ground and boggy sections are common.'),
    false
  ),
  (
    'holandsmelen',
    'holandsmelen',
    'holandsmelen',
    'Holandsmelen',
    'Accessible summit above Haukland and Uttakleiv.',
    'Holandsmelen gives strong beach views from a shorter route, but the upper slopes can still be slippery and exposed.',
    4.2,
    430,
    '2-3 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.520, 68.211), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.493, 68.222), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Stay clear of steep drops near viewpoints.', 'Grass and mud can be slippery after rain.', 'Parking near Haukland and Uttakleiv is busy in summer.'),
    false
  ),
  (
    'hoven-gimsoya',
    'hoven-gimsoya',
    'hoven-gimsoya',
    'Hoven',
    'Short Gimsøya summit hike above Hov.',
    'Hoven is one of the gentler Lofoten mountain hikes, with open coastal views and a relatively short climb from the Hov area.',
    3.6,
    360,
    '2-3 hours round trip',
    'easy',
    extensions.st_setsrid(extensions.st_makepoint(14.204, 68.322), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.230, 68.326), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Open terrain can be windy despite the low height.', 'Respect local paths and grazing areas.', 'Winter ice can make an easy summer route more serious.'),
    false
  ),
  (
    'volandstinden',
    'volandstinden',
    'volandstinden',
    'Volandstinden',
    'Distinctive Flakstadoya summit above coastal terrain.',
    'Volandstinden is a compact but steep hike with strong views toward Ramberg, Skjelfjord and surrounding peaks.',
    6.4,
    460,
    '3-5 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.250, 68.085), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.233, 68.087), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Steep terrain requires dry conditions and careful descent.', 'Route finding can be unclear in places.', 'Avoid exposed sections in strong wind.'),
    false
  ),
  (
    'stornappstinden',
    'stornappstinden',
    'stornappstinden',
    'Stornappstinden',
    'Steep summit above Napp and Nappstraumen.',
    'Stornappstinden is a demanding but popular summit route with a big panorama over central and western Lofoten.',
    4.7,
    720,
    '3-5 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.355, 68.116), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.350, 68.102), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Steep ascent with limited shelter.', 'Loose rock and wet grass can be hazardous.', 'Save this hike for stable weather and clear visibility.'),
    false
  ),
  (
    'helvetestinden',
    'helvetestinden',
    'helvetestinden',
    'Helvetestinden',
    'Remote summit above Bunes Beach, usually starting from Vindstad.',
    'Helvetestinden combines ferry logistics, a beach approach and a steep mountain climb. Plan around boat times and avoid pushing the route in poor weather.',
    8.0,
    600,
    '4-6 hours round trip from Vindstad',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(12.986, 67.989), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(12.960, 67.975), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Check ferry times before starting.', 'Remote route with limited bailout options.', 'Steep slopes above Bunes require dry conditions and good visibility.'),
    false
  ),
  (
    'roren',
    'roren',
    'roren',
    'Røren',
    'Short coastal viewpoint above Ytresand and Fredvang.',
    'Røren is a lower mountain walk with a very good view-to-effort ratio. It is often chosen for sunset, but weather and wind still matter.',
    3.0,
    290,
    '1.5-2.5 hours round trip',
    'easy',
    extensions.st_setsrid(extensions.st_makepoint(13.183, 68.096), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.170, 68.105), 4326)::extensions.geography,
    'Draft starter route uses approximate start and summit coordinates until GPX route data is uploaded. Verify locally before publishing.',
    jsonb_build_array('Stay back from coastal drops and steep grass.', 'Bring a headlamp if hiking for sunset.', 'Respect parking and local access near Ytresand.'),
    false
  )
on conflict (id) do nothing;

insert into public.trails (
  id,
  mountain_id,
  slug,
  name,
  summary,
  description,
  length_km,
  elevation_gain_meters,
  estimated_duration,
  difficulty,
  start_point,
  end_point,
  route_note
) values
  (
    'reinebringen',
    'reinebringen',
    'reinebringen',
    'Reinebringen',
    'Iconic steep stair hike above Reine with one of Lofoten''s most famous fjord views.',
    'Reinebringen climbs steeply from the old road by Ramsviktunnelen to the ridge above Reine, Sakrisøy, Hamnøy and Reinefjorden.',
    2.0,
    448,
    '1-2 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.079083, 67.923017), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.07652, 67.927689), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'ryten-kvalvika',
    'ryten-kvalvika',
    'ryten-kvalvika',
    'Ryten / Kvalvika',
    'Classic hike to the Ryten viewpoint over Kvalvika Beach, with an optional beach extension.',
    'Ryten is a popular summit above Kvalvika Beach, reached from the Fredvang/Innersand area through open coastal terrain.',
    7.5,
    520,
    '4-6 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.135228, 68.099734), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.09263, 68.08904), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'festvagtind',
    'festvagtind',
    'festvagtind',
    'Festvågtind',
    'Short, steep summit hike above Henningsvær with dramatic island views.',
    'Festvågtind rises sharply above the road to Henningsvær and packs a lot of elevation into a short distance.',
    3.3,
    530,
    '2-3 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(14.21396, 68.17105), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.225311, 68.178048), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'offersoykammen',
    'offersoykammen',
    'offersoykammen',
    'Offersøykammen',
    'Compact mountain hike near Leknes with a big view over beaches, fjords and Nappstraumen.',
    'Offersøykammen is a short but sustained climb near the Nappstraumen tunnel and Leknes.',
    2.2,
    410,
    '2-2.5 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.51368, 68.15439), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.501912, 68.161276), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'tjeldbergtind',
    'tjeldbergtind',
    'tjeldbergtind',
    'Tjeldbergtind',
    'Accessible Svolvær-area hike with views over Svolvær, Kabelvåg and Vestfjorden.',
    'Tjeldbergtind is a popular local hike between Svolvær and Kabelvåg.',
    4.7,
    360,
    '1-2 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(14.525517, 68.233184), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.49932, 68.229662), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'himmeltindan',
    'himmeltindan',
    'himmeltindan',
    'Himmeltindan',
    'Long climb from Haukland Beach toward one of Vestvågøy''s biggest viewpoints.',
    'Himmeltindan is one of the major summit hikes in central Lofoten.',
    8.5,
    945,
    '3-5 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.532091, 68.199379), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.573159, 68.221006), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'mannen',
    'mannen',
    'mannen',
    'Mannen',
    'Short Haukland Beach summit hike with strong effort-to-view value.',
    'Mannen starts from the Haukland Beach area and follows an old cart road before climbing grassy slopes to the ridge.',
    3.5,
    400,
    '2-3 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.532091, 68.199379), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.520262, 68.203696), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'munken',
    'munken',
    'munken',
    'Munken',
    'Longer Sørvågen mountain hike through lakes, rock slabs and wild Moskenesøya terrain.',
    'Munken is a more committing hike near Sørvågen through varied terrain with lakes, rocky sections and views toward Munkebu.',
    11.9,
    921,
    '5-7 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.010128, 67.891149), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.019111, 67.93249), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  )
on conflict (id) do nothing;
