-- Initial MVP content for Lofoten Peaks.
-- Safe to rerun after editing the static frontend data.

insert into public.mountains (
  id,
  slug,
  name,
  region,
  height_meters,
  summit,
  difficulty,
  summary,
  description,
  weather_location_id,
  hero_image_path
) values
  (
    'reinebringen',
    'reinebringen',
    'Reinebringen',
    'Moskenesøya, Moskenes',
    484,
    extensions.st_setsrid(extensions.st_makepoint(13.07652, 67.927689), 4326)::extensions.geography,
    'hard',
    'Iconic steep stair hike above Reine with one of Lofoten''s most famous fjord views.',
    'Reinebringen is one of Lofoten''s most photographed hikes, climbing steeply from the old road by Ramsviktunnelen to a panoramic ridge above Reine, Sakrisøy, Hamnøy and Reinefjorden.',
    'west-lofoten',
    '/images/reinebringen-hero.jpg'
  ),
  (
    'ryten-kvalvika',
    'ryten-kvalvika',
    'Ryten / Kvalvika',
    'Flakstadøya, Flakstad',
    543,
    extensions.st_setsrid(extensions.st_makepoint(13.09263, 68.08904), 4326)::extensions.geography,
    'moderate',
    'Classic hike to the Ryten viewpoint over Kvalvika Beach, with optional beach extension.',
    'Ryten is a popular summit above Kvalvika Beach, offering one of the best coastal viewpoints in Lofoten.',
    'west-lofoten',
    '/images/ryten-kvalvika-hero.jpg'
  ),
  (
    'festvagtind',
    'festvagtind',
    'Festvågtind',
    'Austvågøya, Vågan',
    541,
    extensions.st_setsrid(extensions.st_makepoint(14.225311, 68.178048), 4326)::extensions.geography,
    'hard',
    'Short, steep summit hike above Henningsvær with dramatic views over the fishing village.',
    'Festvågtind rises sharply above the road to Henningsvær and is one of the most popular short summit hikes in eastern Lofoten.',
    'east-lofoten',
    '/images/festvagtind-hero.jpg'
  ),
  (
    'offersoykammen',
    'offersoykammen',
    'Offersøykammen',
    'Vestvågøya, Vestvågøy',
    436,
    extensions.st_setsrid(extensions.st_makepoint(13.501912, 68.161276), 4326)::extensions.geography,
    'moderate',
    'Short but steep climb to a panoramic viewpoint over beaches, fjords and the Nappstraumen area.',
    'Offersøykammen is a compact mountain near the Nappstraumen tunnel and Leknes with broad views over beaches, fjords and surrounding mountains.',
    'central-lofoten',
    '/images/offersoykammen-hero.jpg'
  ),
  (
    'tjeldbergtind',
    'tjeldbergtind',
    'Tjeldbergtind',
    'Austvågøya, Vågan',
    367,
    extensions.st_setsrid(extensions.st_makepoint(14.49932, 68.229662), 4326)::extensions.geography,
    'moderate',
    'Accessible Svolvær-area hike with views over Svolvær, Kabelvåg, Vestfjorden and surrounding peaks.',
    'Tjeldbergtind is a popular local hike between Svolvær and Kabelvåg with a rewarding 360-degree view.',
    'east-lofoten',
    '/images/tjeldbergtind-hero.jpg'
  ),
  (
    'himmeltindan',
    'himmeltindan',
    'Himmeltindan',
    'Vestvågøya, Vestvågøy',
    962,
    extensions.st_setsrid(extensions.st_makepoint(13.573159, 68.221006), 4326)::extensions.geography,
    'hard',
    'Highest mountain on Vestvågøy, climbing steeply from Haukland Beach to a major Lofoten panorama.',
    'Himmeltindan is one of the major summit hikes in central Lofoten and climbs steadily from Haukland Beach toward the upper ridge.',
    'central-lofoten',
    '/images/himmeltindan-hero.jpg'
  ),
  (
    'mannen',
    'mannen',
    'Mannen',
    'Vestvågøya, Vestvågøy',
    400,
    extensions.st_setsrid(extensions.st_makepoint(13.520262, 68.203696), 4326)::extensions.geography,
    'moderate',
    'Short Haukland Beach summit hike with big views over Haukland, Uttakleiv and Vik.',
    'Mannen is a relatively accessible summit starting from the Haukland Beach area with excellent beach and mountain views.',
    'central-lofoten',
    '/images/mannen-hero.jpg'
  ),
  (
    'munken',
    'munken',
    'Munken',
    'Moskenesøya, Moskenes',
    769,
    extensions.st_setsrid(extensions.st_makepoint(13.019111, 67.93249), 4326)::extensions.geography,
    'hard',
    'Longer mountain hike from Sørvågen via lakes and Munkebu toward a wild Moskenesøya panorama.',
    'Munken is a longer and more committing hike near Sørvågen through lakes, rocky sections, boggy areas and views toward Munkebu.',
    'west-lofoten',
    '/images/munken-hero.jpg'
  )
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  region = excluded.region,
  height_meters = excluded.height_meters,
  summit = excluded.summit,
  difficulty = excluded.difficulty,
  summary = excluded.summary,
  description = excluded.description,
  weather_location_id = excluded.weather_location_id,
  hero_image_path = excluded.hero_image_path;

insert into public.trails (
  id,
  mountain_id,
  slug,
  name,
  summary,
  description,
  length_km,
  elevation_gain_meters,
  estimated_duration,
  difficulty,
  start_point,
  end_point,
  route_note
) values
  (
    'reinebringen',
    'reinebringen',
    'reinebringen',
    'Reinebringen',
    'Iconic steep stair hike above Reine with one of Lofoten''s most famous fjord views.',
    'Reinebringen climbs steeply from the old road by Ramsviktunnelen to the ridge above Reine, Sakrisøy, Hamnøy and Reinefjorden.',
    2.0,
    448,
    '1-2 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.079083, 67.923017), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.07652, 67.927689), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'ryten-kvalvika',
    'ryten-kvalvika',
    'ryten-kvalvika',
    'Ryten / Kvalvika',
    'Classic hike to the Ryten viewpoint over Kvalvika Beach, with an optional beach extension.',
    'Ryten is a popular summit above Kvalvika Beach, reached from the Fredvang/Innersand area through open coastal terrain.',
    7.5,
    520,
    '4-6 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.135228, 68.099734), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.09263, 68.08904), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'festvagtind',
    'festvagtind',
    'festvagtind',
    'Festvågtind',
    'Short, steep summit hike above Henningsvær with dramatic island views.',
    'Festvågtind rises sharply above the road to Henningsvær and packs a lot of elevation into a short distance.',
    3.3,
    530,
    '2-3 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(14.21396, 68.17105), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.225311, 68.178048), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'offersoykammen',
    'offersoykammen',
    'offersoykammen',
    'Offersøykammen',
    'Compact mountain hike near Leknes with a big view over beaches, fjords and Nappstraumen.',
    'Offersøykammen is a short but sustained climb near the Nappstraumen tunnel and Leknes.',
    2.2,
    410,
    '2-2.5 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.51368, 68.15439), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.501912, 68.161276), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'tjeldbergtind',
    'tjeldbergtind',
    'tjeldbergtind',
    'Tjeldbergtind',
    'Accessible Svolvær-area hike with views over Svolvær, Kabelvåg and Vestfjorden.',
    'Tjeldbergtind is a popular local hike between Svolvær and Kabelvåg.',
    4.7,
    360,
    '1-2 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(14.525517, 68.233184), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(14.49932, 68.229662), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'himmeltindan',
    'himmeltindan',
    'himmeltindan',
    'Himmeltindan',
    'Long climb from Haukland Beach toward one of Vestvågøy''s biggest viewpoints.',
    'Himmeltindan is one of the major summit hikes in central Lofoten.',
    8.5,
    945,
    '3-5 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.532091, 68.199379), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.573159, 68.221006), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'mannen',
    'mannen',
    'mannen',
    'Mannen',
    'Short Haukland Beach summit hike with strong effort-to-view value.',
    'Mannen starts from the Haukland Beach area and follows an old cart road before climbing grassy slopes to the ridge.',
    3.5,
    400,
    '2-3 hours round trip',
    'moderate',
    extensions.st_setsrid(extensions.st_makepoint(13.532091, 68.199379), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.520262, 68.203696), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  ),
  (
    'munken',
    'munken',
    'munken',
    'Munken',
    'Longer Sørvågen mountain hike through lakes, rock slabs and wild Moskenesøya terrain.',
    'Munken is a more committing hike near Sørvågen through varied terrain with lakes, rocky sections and views toward Munkebu.',
    11.9,
    921,
    '5-7 hours round trip',
    'hard',
    extensions.st_setsrid(extensions.st_makepoint(13.010128, 67.891149), 4326)::extensions.geography,
    extensions.st_setsrid(extensions.st_makepoint(13.019111, 67.93249), 4326)::extensions.geography,
    'Route line uses saved route coordinate data for planning preview. Verify locally before hiking.'
  )
on conflict (id) do update set
  mountain_id = excluded.mountain_id,
  slug = excluded.slug,
  name = excluded.name,
  summary = excluded.summary,
  description = excluded.description,
  length_km = excluded.length_km,
  elevation_gain_meters = excluded.elevation_gain_meters,
  estimated_duration = excluded.estimated_duration,
  difficulty = excluded.difficulty,
  start_point = excluded.start_point,
  end_point = excluded.end_point,
  route_note = excluded.route_note;
